# Generated by Django 2.2 on 2019-12-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191212_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority',), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
