# Generated by Django 2.2 on 2019-12-12 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191212_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='holder',
            field=models.CharField(default='Vera', max_length=100),
            preserve_default=False,
        ),
    ]
