# Generated by Django 2.2 on 2019-12-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191219_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
