# Generated by Django 2.2 on 2019-12-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191219_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='books.Author'),
        ),
    ]
