# Generated by Django 2.2 on 2019-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191219_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='books_cover/'),
        ),
    ]
