# Generated by Django 2.2 on 2019-12-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
